name: Install dependencies

on:
    workflow_dispatch:

jobs:
    setup:
        runs-on: ubuntu-latest

        steps:
            - name: Code checkout
              uses: actions/checkout@v4
                 
            - name: node config
              uses: actions/setup-node@v4
              with:
                node-version: 'latest'
            
            - name: Install vite and dep
              run: |
                npm install -g create-vite
                npm install node
        
            - name: App build
              run: npm run build
